{
  "formatVersion": "1.1",
  "component": {
    "group": "icu.ketal.katexmath",
    "module": "KaTeXMath-compose",
    "version": "0.0.1-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "icu.ketal.katexmath",
          "module": "KaTeXMath-core",
          "version": {
            "requires": "0.0.1-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "KaTeXMath-compose-0.0.1-alpha06.aar",
          "url": "KaTeXMath-compose-0.0.1-alpha06.aar",
          "size": 14373,
          "sha512": "aad473486ba038d61c6bd5ef3df055e667ee18bb812a78667113f3dcec1f7e0b4d4643e6f5669d60164858f9ded4ccd555fd0f632db6f37eded851d40445367c",
          "sha256": "da4187f2a2515a3eb7c4e6da918c4b2fb5a8463e353b72b41575d2bdf752c24c",
          "sha1": "b34da91c814352dc4af8b0501540342051f9749c",
          "md5": "2c44826529f16f306fcfa3a31f09635a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "icu.ketal.katexmath",
          "module": "KaTeXMath-core",
          "version": {
            "requires": "0.0.1-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "KaTeXMath-compose-0.0.1-alpha06.aar",
          "url": "KaTeXMath-compose-0.0.1-alpha06.aar",
          "size": 14373,
          "sha512": "aad473486ba038d61c6bd5ef3df055e667ee18bb812a78667113f3dcec1f7e0b4d4643e6f5669d60164858f9ded4ccd555fd0f632db6f37eded851d40445367c",
          "sha256": "da4187f2a2515a3eb7c4e6da918c4b2fb5a8463e353b72b41575d2bdf752c24c",
          "sha1": "b34da91c814352dc4af8b0501540342051f9749c",
          "md5": "2c44826529f16f306fcfa3a31f09635a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KaTeXMath-compose-0.0.1-alpha06-sources.jar",
          "url": "KaTeXMath-compose-0.0.1-alpha06-sources.jar",
          "size": 3459,
          "sha512": "62957033583ac205b5c9d53f06dfda177779253cf33d31c003f5f4ae290fe709aee49b37a79f5e0f2230c0fc8a1fe829b69177f6e00ed5de249caa2c7080a947",
          "sha256": "265247954494281d1bd861b0b3c79c3545b56ddb97d0d4f722cda752b32e0697",
          "sha1": "42228e05751983e2aa10cb0901c3c6962038afdc",
          "md5": "9965f1eb4281640463faa9a3ef6ca9d0"
        }
      ]
    }
  ]
}
