{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.dokar3.fork",
    "module": "sheets-m3",
    "version": "0.6.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.github.dokar3.fork",
          "module": "sheets-core",
          "version": {
            "requires": "0.6.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "sheets-m3-metadata.jar",
          "url": "sheets-m3-0.6.0-alpha06.jar",
          "size": 3841,
          "sha512": "b0c740c1affb54bbb91dfb38543f65ee3ee9f8276f27bae6a91bb0b69c95046e6afa6526f4732e7ff8839a6d5725b894b4c7cef5a3d7b49355ac0c52b26b86e6",
          "sha256": "aeecf614a712da44f54dc991a87b00df590160a6c7508efdb95b502c84490258",
          "sha1": "3c731bb4d63cce27927a0932dbc60b7481f50ddd",
          "md5": "bbec3f5111a0a431eb6a5972684d4670"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "sheets-m3-kotlin-sources.jar",
          "url": "sheets-m3-0.6.0-alpha06-sources.jar",
          "size": 3588,
          "sha512": "962646ee391d6f555adb627be6852b7ef3ed5328abe10b6d496d9ae37d241c738b0ef0a63a40f404701075d38587586c4e8676b8eefd1d53632ded129f65183e",
          "sha256": "37fb04b9e5dd2dd7c1d7c1fa81b21751da79e5ae0ec035eafb681294cb177231",
          "sha1": "9346f7a6cec183353253aaf21f102b304ca936d7",
          "md5": "7a4ccd3ffd8adb8ecc88907065045b20"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sheets-m3-android/0.6.0-alpha06/sheets-m3-android-0.6.0-alpha06.module",
        "group": "io.github.dokar3.fork",
        "module": "sheets-m3-android",
        "version": "0.6.0-alpha06"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sheets-m3-android/0.6.0-alpha06/sheets-m3-android-0.6.0-alpha06.module",
        "group": "io.github.dokar3.fork",
        "module": "sheets-m3-android",
        "version": "0.6.0-alpha06"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sheets-m3-android/0.6.0-alpha06/sheets-m3-android-0.6.0-alpha06.module",
        "group": "io.github.dokar3.fork",
        "module": "sheets-m3-android",
        "version": "0.6.0-alpha06"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../sheets-m3-desktop/0.6.0-alpha06/sheets-m3-desktop-0.6.0-alpha06.module",
        "group": "io.github.dokar3.fork",
        "module": "sheets-m3-desktop",
        "version": "0.6.0-alpha06"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../sheets-m3-desktop/0.6.0-alpha06/sheets-m3-desktop-0.6.0-alpha06.module",
        "group": "io.github.dokar3.fork",
        "module": "sheets-m3-desktop",
        "version": "0.6.0-alpha06"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../sheets-m3-desktop/0.6.0-alpha06/sheets-m3-desktop-0.6.0-alpha06.module",
        "group": "io.github.dokar3.fork",
        "module": "sheets-m3-desktop",
        "version": "0.6.0-alpha06"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../sheets-m3-wasm-js/0.6.0-alpha06/sheets-m3-wasm-js-0.6.0-alpha06.module",
        "group": "io.github.dokar3.fork",
        "module": "sheets-m3-wasm-js",
        "version": "0.6.0-alpha06"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../sheets-m3-wasm-js/0.6.0-alpha06/sheets-m3-wasm-js-0.6.0-alpha06.module",
        "group": "io.github.dokar3.fork",
        "module": "sheets-m3-wasm-js",
        "version": "0.6.0-alpha06"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../sheets-m3-wasm-js/0.6.0-alpha06/sheets-m3-wasm-js-0.6.0-alpha06.module",
        "group": "io.github.dokar3.fork",
        "module": "sheets-m3-wasm-js",
        "version": "0.6.0-alpha06"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../sheets-m3-wasm-js/0.6.0-alpha06/sheets-m3-wasm-js-0.6.0-alpha06.module",
        "group": "io.github.dokar3.fork",
        "module": "sheets-m3-wasm-js",
        "version": "0.6.0-alpha06"
      }
    }
  ]
}
