{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sheets/0.6.0-alpha06/sheets-0.6.0-alpha06.module",
    "group": "io.github.dokar3.fork",
    "module": "sheets",
    "version": "0.6.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.dokar3.fork",
          "module": "sheets-core",
          "version": {
            "requires": "0.6.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "sheets-release.aar",
          "url": "sheets-android-0.6.0-alpha06.aar",
          "size": 16959,
          "sha512": "23ae00a599de0e08dccaa4204c4296bd7c57bcb7bec41ab0197d5060f050da56ecaacff27b0599d9abf4e3b21ac6bc3aaad9a19b1c9b36b6c6dbde4212cbcf29",
          "sha256": "c33017c59b0c46970c268ac554d84e7e41bd10c13c7aa5fc58b5bc08b73fd22d",
          "sha1": "de01979404c6742ebbe5afcb29f5e898ecd0625e",
          "md5": "e73dd84ed659e7757a61e0783b6f14aa"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.dokar3.fork",
          "module": "sheets-core",
          "version": {
            "requires": "0.6.0-alpha06"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.6.11"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sheets-release.aar",
          "url": "sheets-android-0.6.0-alpha06.aar",
          "size": 16959,
          "sha512": "23ae00a599de0e08dccaa4204c4296bd7c57bcb7bec41ab0197d5060f050da56ecaacff27b0599d9abf4e3b21ac6bc3aaad9a19b1c9b36b6c6dbde4212cbcf29",
          "sha256": "c33017c59b0c46970c268ac554d84e7e41bd10c13c7aa5fc58b5bc08b73fd22d",
          "sha1": "de01979404c6742ebbe5afcb29f5e898ecd0625e",
          "md5": "e73dd84ed659e7757a61e0783b6f14aa"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "sheets-android-sources.jar",
          "url": "sheets-android-0.6.0-alpha06-sources.jar",
          "size": 3276,
          "sha512": "50b58759610aee9fe587c30381c5d6b78f094f334da5f612dd39b5207457290284ce475dac4f64098460087e709f5026ee35b235bdd2063d0c04caccd3231c6c",
          "sha256": "89117539ef58082597c880a358f22e8c6ca9789572cd09256fa438241df08697",
          "sha1": "e6dbe21f4766b63222087501e8c4f16e9b5107d8",
          "md5": "5b6025674e45ec64c1b2dbaa33c68a87"
        }
      ]
    }
  ]
}
