{
  "formatVersion": "1.1",
  "component": {
    "group": "icu.ketal.katexmath",
    "module": "KaTeXMath",
    "version": "0.0.1-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "KaTeXMath-0.0.1-alpha01.aar",
          "url": "KaTeXMath-0.0.1-alpha01.aar",
          "size": 2783030,
          "sha512": "bc344b8cde4d762f2584c37f7bb0aef73288d3e2ba4c53ec656c8215f48741efd95955919108ad830304d1994e0fe7856099bc2a87185ead99ae2001e1914cd9",
          "sha256": "810d4fcfffc167b696ecb13bf43e4e727d09b394bbe027cb5f3ad2a5e52bc98b",
          "sha1": "267d092756db22714428bc43bba5ed7a244c765a",
          "md5": "914cfa367de492ac7b82ca9dd6f9cb5b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.rikka.ndk.thirdparty",
          "module": "cxx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "KaTeXMath-0.0.1-alpha01.aar",
          "url": "KaTeXMath-0.0.1-alpha01.aar",
          "size": 2783030,
          "sha512": "bc344b8cde4d762f2584c37f7bb0aef73288d3e2ba4c53ec656c8215f48741efd95955919108ad830304d1994e0fe7856099bc2a87185ead99ae2001e1914cd9",
          "sha256": "810d4fcfffc167b696ecb13bf43e4e727d09b394bbe027cb5f3ad2a5e52bc98b",
          "sha1": "267d092756db22714428bc43bba5ed7a244c765a",
          "md5": "914cfa367de492ac7b82ca9dd6f9cb5b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KaTeXMath-0.0.1-alpha01-sources.jar",
          "url": "KaTeXMath-0.0.1-alpha01-sources.jar",
          "size": 66025,
          "sha512": "3a20c5b7433700eec92ed4a6e20b5f87b2175cb4a4c8b615e78f41b9520251d6a24f75a932661f6de921be07777d29f79bdc2cabe1774f02fb40955e3f30f200",
          "sha256": "f94a8ca52c15597f86e2684208324daa33f7473e38d631d8243514b20081a387",
          "sha1": "b2b302743a66d9801c9fd6564d4637694b8f6002",
          "md5": "b4cd532b92a793f1ae1589d983c6a8ab"
        }
      ]
    }
  ]
}
