{
  "formatVersion": "1.1",
  "component": {
    "group": "icu.ketal.katexmath",
    "module": "KaTeXMath-core",
    "version": "0.0.1-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "KaTeXMath-core-0.0.1-alpha04.aar",
          "url": "KaTeXMath-core-0.0.1-alpha04.aar",
          "size": 2782086,
          "sha512": "c02a41444410001451f4eda4c48fa56af6bf8c625418fa102d956e4b2918f4562fbc1993fdc5be6123caa20fd8e996d30d4e9eee2766c690f27a846fdd9d1f8b",
          "sha256": "d5490e41fb179bbcfb666342124ade440c9e3d176a270224421f14a30f262311",
          "sha1": "7c1934d2ef68ba0042a7e891c03e1255a32b1358",
          "md5": "9771e945347c56d83a74d2ec90ff8028"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.rikka.ndk.thirdparty",
          "module": "cxx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "KaTeXMath-core-0.0.1-alpha04.aar",
          "url": "KaTeXMath-core-0.0.1-alpha04.aar",
          "size": 2782086,
          "sha512": "c02a41444410001451f4eda4c48fa56af6bf8c625418fa102d956e4b2918f4562fbc1993fdc5be6123caa20fd8e996d30d4e9eee2766c690f27a846fdd9d1f8b",
          "sha256": "d5490e41fb179bbcfb666342124ade440c9e3d176a270224421f14a30f262311",
          "sha1": "7c1934d2ef68ba0042a7e891c03e1255a32b1358",
          "md5": "9771e945347c56d83a74d2ec90ff8028"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KaTeXMath-core-0.0.1-alpha04-sources.jar",
          "url": "KaTeXMath-core-0.0.1-alpha04-sources.jar",
          "size": 65677,
          "sha512": "a5ee7e70cfae765025dba81f4ad2d8b27e2398b2d99ee83aec0767dcf6b135f539a6d39268ed0e5e4ea1fff3e943e2589def04d4f4e316a1181c577c1fc63c0a",
          "sha256": "701bb26785fa8d6d4f49d70392d1e62482153ff38888eaf7e91da6769ba7ae36",
          "sha1": "b576cc77033adef5adaaae6778726249e2d52a2b",
          "md5": "5513c26e90f9e9ac4857916f46431896"
        }
      ]
    }
  ]
}
