{
  "formatVersion": "1.1",
  "component": {
    "group": "icu.ketal.katexmath",
    "module": "KaTeXMath-core",
    "version": "0.0.1-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "KaTeXMath-core-0.0.1-alpha03.aar",
          "url": "KaTeXMath-core-0.0.1-alpha03.aar",
          "size": 2783231,
          "sha512": "1ee9a781813d289721cb1f021ede712ca00245f851aa7e0be59d859fe4af34b72fbd9c94e1584692bf55b898cc3bdb6dfd38a8ad93d11fed680e71f7743c9723",
          "sha256": "ec3cf2441bafe4e27c4ed78ff8d32192879125a80346733913993b676d6dd1e5",
          "sha1": "9536bcb19cdbfa9b21c485084d209851d508a958",
          "md5": "b22044d26235495f1b018b5a8654bfe5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.rikka.ndk.thirdparty",
          "module": "cxx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "KaTeXMath-core-0.0.1-alpha03.aar",
          "url": "KaTeXMath-core-0.0.1-alpha03.aar",
          "size": 2783231,
          "sha512": "1ee9a781813d289721cb1f021ede712ca00245f851aa7e0be59d859fe4af34b72fbd9c94e1584692bf55b898cc3bdb6dfd38a8ad93d11fed680e71f7743c9723",
          "sha256": "ec3cf2441bafe4e27c4ed78ff8d32192879125a80346733913993b676d6dd1e5",
          "sha1": "9536bcb19cdbfa9b21c485084d209851d508a958",
          "md5": "b22044d26235495f1b018b5a8654bfe5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KaTeXMath-core-0.0.1-alpha03-sources.jar",
          "url": "KaTeXMath-core-0.0.1-alpha03-sources.jar",
          "size": 65677,
          "sha512": "a5ee7e70cfae765025dba81f4ad2d8b27e2398b2d99ee83aec0767dcf6b135f539a6d39268ed0e5e4ea1fff3e943e2589def04d4f4e316a1181c577c1fc63c0a",
          "sha256": "701bb26785fa8d6d4f49d70392d1e62482153ff38888eaf7e91da6769ba7ae36",
          "sha1": "b576cc77033adef5adaaae6778726249e2d52a2b",
          "md5": "5513c26e90f9e9ac4857916f46431896"
        }
      ]
    }
  ]
}
