{
  "formatVersion": "1.1",
  "component": {
    "group": "icu.ketal.katexmath",
    "module": "KaTeXMath-compose",
    "version": "0.0.1-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "icu.ketal.katexmath",
          "module": "KaTeXMath-core",
          "version": {
            "requires": "0.0.1-alpha07"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "KaTeXMath-compose-0.0.1-alpha07.aar",
          "url": "KaTeXMath-compose-0.0.1-alpha07.aar",
          "size": 14603,
          "sha512": "bef8f026b42aec6e23719fc6000c9387c67a3d5e58fa6bd785259c971f19b3593ac4cb9457e153b6a4a72c3f377dba93aca41bb7447142264e12ec0ff784ea8a",
          "sha256": "9dfbd5931a924d712f06df0244dfaf3f03f9915cf752c4964bb254e7856fd3dc",
          "sha1": "43d97cb1a20b6aa411508ad730ff5f756aebc248",
          "md5": "15050efe95cfc367912139f5b54d5002"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.03.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "icu.ketal.katexmath",
          "module": "KaTeXMath-core",
          "version": {
            "requires": "0.0.1-alpha07"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "KaTeXMath-compose-0.0.1-alpha07.aar",
          "url": "KaTeXMath-compose-0.0.1-alpha07.aar",
          "size": 14603,
          "sha512": "bef8f026b42aec6e23719fc6000c9387c67a3d5e58fa6bd785259c971f19b3593ac4cb9457e153b6a4a72c3f377dba93aca41bb7447142264e12ec0ff784ea8a",
          "sha256": "9dfbd5931a924d712f06df0244dfaf3f03f9915cf752c4964bb254e7856fd3dc",
          "sha1": "43d97cb1a20b6aa411508ad730ff5f756aebc248",
          "md5": "15050efe95cfc367912139f5b54d5002"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KaTeXMath-compose-0.0.1-alpha07-sources.jar",
          "url": "KaTeXMath-compose-0.0.1-alpha07-sources.jar",
          "size": 3472,
          "sha512": "37609967def8f41a9aec61f4ce5d44453be679f8ed5a6e67b385f352b9c14b72958ee1ac098f3d172f3822fba191e3bcac4ef2605c25ec61ef7648f7218d299b",
          "sha256": "89377b00e7575990e8947fafeee01d28fcf0d19056e931b29f7a4e6aea1d53dc",
          "sha1": "0d7ffcf24c64fb80bbbe567c66fb51e2ba2b1780",
          "md5": "f64a0e11fb100db819b9ba6ddc66de88"
        }
      ]
    }
  ]
}
