{
  "formatVersion": "1.1",
  "component": {
    "group": "icu.ketal.katexmath",
    "module": "KaTeXMath-core",
    "version": "0.0.1-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "KaTeXMath-core-0.0.1-alpha06.aar",
          "url": "KaTeXMath-core-0.0.1-alpha06.aar",
          "size": 2783335,
          "sha512": "4e81128c67c32bfaedceec02abac02cf0221e4a710fff71bbc64d1324b01328ff6c8d48013bee7a36de905ef72923061f01ca20ed5a9cc3284a46edbe95f36af",
          "sha256": "56c9c6e3565abcbee68ecc913345ff24989a07c2af9f5da476d1f3ecc787f9fd",
          "sha1": "7246f95af796add73abe1d3e3144bdc635441770",
          "md5": "bd7716591332cca34f43f6ef9d621322"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.rikka.ndk.thirdparty",
          "module": "cxx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "KaTeXMath-core-0.0.1-alpha06.aar",
          "url": "KaTeXMath-core-0.0.1-alpha06.aar",
          "size": 2783335,
          "sha512": "4e81128c67c32bfaedceec02abac02cf0221e4a710fff71bbc64d1324b01328ff6c8d48013bee7a36de905ef72923061f01ca20ed5a9cc3284a46edbe95f36af",
          "sha256": "56c9c6e3565abcbee68ecc913345ff24989a07c2af9f5da476d1f3ecc787f9fd",
          "sha1": "7246f95af796add73abe1d3e3144bdc635441770",
          "md5": "bd7716591332cca34f43f6ef9d621322"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KaTeXMath-core-0.0.1-alpha06-sources.jar",
          "url": "KaTeXMath-core-0.0.1-alpha06-sources.jar",
          "size": 65720,
          "sha512": "1036581e49255209e96452dd61efe4492fd0c07445ffb0370ce6fe1d539158dcfc641f140c28271c10524c26c4dc182504af3db1a7540ea9f9ccf8c412745b51",
          "sha256": "5bb886b985ee5f2e3a378cb9f137aa0e9f8ffa8155c605daab93f348510d3951",
          "sha1": "0fe18273a1dd085c5ab8ca6a829d900846fc37a8",
          "md5": "2805a5658f287ad1939219e526b840bb"
        }
      ]
    }
  ]
}
