{
  "formatVersion": "1.1",
  "component": {
    "group": "icu.ketal.katexmath",
    "module": "KaTeXMath-compose",
    "version": "0.0.1-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "KaTeXMath-compose-0.0.1-alpha04.aar",
          "url": "KaTeXMath-compose-0.0.1-alpha04.aar",
          "size": 14451,
          "sha512": "54a7a5beaa094139e74b9587fb3b07ae8a166b75929acc28dc948c55cf81af856bd0994edde99470f31e7ef2f69ecc39c015c25d726feae8d8e1682e3efb7e67",
          "sha256": "22730e1d70e97df22c7b551f78c1ad0ce9b875db2dc711abd43039b931c6b2c9",
          "sha1": "fb13d8caf2523a8e1cf7318bb634d924c535052e",
          "md5": "24742b355a31d06a5d4e8973e8d96cab"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "icu.ketal.katexmath",
          "module": "KaTeXMath-core",
          "version": {
            "requires": "0.0.1-alpha04"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.12.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "KaTeXMath-compose-0.0.1-alpha04.aar",
          "url": "KaTeXMath-compose-0.0.1-alpha04.aar",
          "size": 14451,
          "sha512": "54a7a5beaa094139e74b9587fb3b07ae8a166b75929acc28dc948c55cf81af856bd0994edde99470f31e7ef2f69ecc39c015c25d726feae8d8e1682e3efb7e67",
          "sha256": "22730e1d70e97df22c7b551f78c1ad0ce9b875db2dc711abd43039b931c6b2c9",
          "sha1": "fb13d8caf2523a8e1cf7318bb634d924c535052e",
          "md5": "24742b355a31d06a5d4e8973e8d96cab"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KaTeXMath-compose-0.0.1-alpha04-sources.jar",
          "url": "KaTeXMath-compose-0.0.1-alpha04-sources.jar",
          "size": 3606,
          "sha512": "071664a23f99df6c781999196cdab73000bf5c6ee01cd0c2232080ea8bc61214c88e2b69deb9abe1c64e7c04860dcd8b049808a44a6e22e0d2f5233ea737e1d4",
          "sha256": "4e134408d95b6027cf96a027e05e66f57e24a862876f96f518326256317cb5c4",
          "sha1": "b6e2fc0e7dfc3e5e582599d8957c13af96e11f9f",
          "md5": "51e338cb276dfe800ca21aa6c995b708"
        }
      ]
    }
  ]
}
